# Generated by Django 3.2.3 on 2021-07-24 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='email address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('I prefer not to say', 'I prefer not to say')], max_length=20)),
                ('phone', models.IntegerField()),
                ('wardno', models.IntegerField()),
                ('Birth_date', models.DateField(blank=True, help_text='YY-MM-DD')),
                ('grampanchayat', models.CharField(help_text='Enter your panchayat', max_length=40)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='service_A',
            fields=[
                ('ration_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_image', models.ImageField(blank=True, upload_to='images/')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('I prefer not to say', 'I prefer not to say')], max_length=20)),
                ('wardno', models.IntegerField(default=0)),
                ('grampanchayat', models.CharField(blank=True, choices=[('Aloor', 'Aloor'), ('Harkur', 'Harkur')], max_length=40)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('village', models.CharField(max_length=150, verbose_name='address')),
                ('city', models.CharField(default='kundapura', max_length=100, verbose_name='city')),
                ('state', models.CharField(choices=[('KARNATAKA', 'KARNATAKA'), ('TAMILNADU', 'TAMILNADU')], max_length=50)),
                ('pin_code', models.CharField(max_length=100, verbose_name='pin_code')),
                ('adhar_no', models.CharField(default='', max_length=12)),
                ('adhar_img', models.ImageField(blank=True, upload_to='images/')),
                ('incom_proof', models.ImageField(default='', upload_to='images/')),
                ('vote', models.ImageField(default='', upload_to='images/')),
                ('apply_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('requirements', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('wardno', models.IntegerField(default=0)),
                ('grampanchayat', models.CharField(max_length=50)),
                ('rate', models.TextField()),
                ('adinfo', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('I prefer not to say', 'I prefer not to say')], max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('grampanchayat', models.CharField(max_length=50)),
                ('wardno', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('adinfo', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaints_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('I prefer not to say', 'I prefer not to say')], max_length=20)),
                ('wardno', models.IntegerField(default=0)),
                ('grampanchayat', models.CharField(blank=True, max_length=40)),
                ('complaint', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
