# Generated by Django 3.2.3 on 2021-07-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_a',
            name='service_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='myapp.service'),
        ),
    ]
