# Generated by Django 3.2.3 on 2021-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service_a_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_a',
            name='apply_date',
            field=models.DateField(),
        ),
    ]
