# Generated by Django 3.2.3 on 2021-07-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_service_a_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_a',
            name='service_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='myapp.service'),
        ),
    ]
