# Generated by Django 3.2.3 on 2021-06-04 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='GramPanchayat',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
