# Generated by Django 3.2.3 on 2021-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_service_a_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_a',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='myimage'),
        ),
    ]
