# Generated by Django 3.2.3 on 2021-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_service_a_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_a',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
