# Generated by Django 3.2.3 on 2021-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_service_a_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_a',
            name='adhar_img',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service_a',
            name='incom_proof',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service_a',
            name='user_image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service_a',
            name='vote',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
