# Generated by Django 3.2.3 on 2021-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210805_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_a',
            name='apply_date',
            field=models.DateField(null=True),
        ),
    ]
