# Generated by Django 3.2.3 on 2021-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_service_a_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('karnataka', 'karnataka'), ('andrapradesh', 'andrapradesh')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('panchayat', models.CharField(choices=[('aloor', 'aloor'), ('kota', 'kota')], max_length=100)),
                ('job_panchayat', models.CharField(choices=[('Aloor', 'Aloor'), ('Kota', 'Kota'), ('Andrapradesh', 'Andrapradesh')], max_length=100)),
                ('profile_img', models.ImageField(blank=True, upload_to='profileimg')),
                ('documnet', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
