# Generated by Django 3.2.3 on 2021-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_service_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_b',
            name='gender',
            field=models.CharField(choices=[('MAKE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50),
        ),
    ]
