# Generated by Django 3.2.3 on 2021-08-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_service_b_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_b',
            old_name='documnet',
            new_name='document',
        ),
    ]
