# Generated by Django 3.2.3 on 2021-08-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_documnet_service_b_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgsall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allimg', models.ImageField(blank=True, upload_to='allimg')),
                ('document', models.FileField(blank=True, upload_to='document')),
            ],
        ),
        migrations.CreateModel(
            name='service_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MAKE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('village', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('karnataka', 'karnataka'), ('andrapradesh', 'andrapradesh')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('panchayat', models.CharField(choices=[('aloor', 'aloor'), ('kota', 'kota')], max_length=100)),
            ],
        ),
    ]
