# Generated by Django 3.2.3 on 2021-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grampanchayat',
            field=models.CharField(default='gram', max_length=122),
        ),
    ]
